CREATE DATABASE XesterUI;
use XesterUI;

SET default_storage_engine=INNODB;

CREATE TABLE X_STATUS (
  ID int(11) NOT NULL AUTO_INCREMENT,
  Status varchar(50) NOT NULL,
  HtmlColor varchar(10) Not NULL,
  HTML_Description varchar(20) Not NULL,
  PRIMARY KEY (ID),
  UNIQUE (Status),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE X_STATUS AUTO_INCREMENT=100;

CREATE TABLE X_RESULT (
  ID int(11) NOT NULL AUTO_INCREMENT,
  Name varchar(50) NOT NULL,
  HtmlColor varchar(10) Not NULL,
  HTML_Description varchar(20) Not NULL,
  PRIMARY KEY (ID),
  UNIQUE (Name),
  UNIQUE (HtmlColor),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE X_RESULT AUTO_INCREMENT=100;

CREATE TABLE QUEUE_MANAGER (
  ID int(11) NOT NULL AUTO_INCREMENT,
  Status_ID int(11) NOT NULL,
  Wait int(11) NOT NULL,
  Log_File varchar(255),
  PRIMARY KEY (ID),
  FOREIGN KEY(Status_ID) REFERENCES X_STATUS(ID),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE TARGET_DIRECTORIES (
  ID int(11) NOT NULL AUTO_INCREMENT,
  Directory varchar(255) NOT NULL,
  Status_ID int(11) NOT NULL,
  PRIMARY KEY (ID),  
  FOREIGN KEY(Status_ID) REFERENCES X_STATUS(ID),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE TESTS (
  ID int(11) NOT NULL AUTO_INCREMENT,
  Target_ID int(11) NOT NULL,
  Status_ID int(11) NOT NULL,
  RESULT_ID int(11) NOT NULL,
  Log_file varchar(255) NOT NULL,
  XML_file varchar(255) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (Target_ID) REFERENCES TARGET_DIRECTORIES(ID),
  FOREIGN KEY(Status_ID) REFERENCES X_STATUS(ID),
  FOREIGN KEY(RESULT_ID) REFERENCES X_RESULT(ID),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
