CREATE DATABASE XesterUI;
use XesterUI;

SET default_storage_engine=INNODB;

CREATE TABLE X_STATUS (
  ID int(11) NOT NULL AUTO_INCREMENT,
  Status varchar(50) NOT NULL,
  HtmlColor varchar(10) Not NULL,
  HTML_Description varchar(20) Not NULL,
  PRIMARY KEY (ID),
  UNIQUE (Status),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE X_STATUS AUTO_INCREMENT=100;

CREATE TABLE X_RESULT (
  ID int(11) NOT NULL AUTO_INCREMENT,
  Name varchar(50) NOT NULL,
  HtmlColor varchar(10) Not NULL,
  HTML_Description varchar(20) Not NULL,
  PRIMARY KEY (ID),
  UNIQUE (Name),
  UNIQUE (HtmlColor),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE X_RESULT AUTO_INCREMENT=100;

CREATE TABLE QUEUE_MANAGER (
  ID int(11) NOT NULL AUTO_INCREMENT,
  STATUS_ID int(11) NOT NULL,
  Wait int(11) NOT NULL,
  Log_File varchar(255),
  PRIMARY KEY (ID),
  FOREIGN KEY(STATUS_ID) REFERENCES X_STATUS(ID),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE TESTRUN_MANAGER (
  ID int(11) NOT NULL AUTO_INCREMENT,
  STATUS_ID int(11) NOT NULL,
  Wait int(11) NOT NULL,
  Max_Concurrent int(11) NOT NULL,
  Log_File varchar(255),
  PRIMARY KEY (ID),
  FOREIGN KEY(STATUS_ID) REFERENCES X_STATUS(ID),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE PASSWORDS (
  ID int(11) NOT NULL AUTO_INCREMENT,
  Username varchar(255) NOT NULL,
  Password varchar(255) NOT NULL,
  PRIMARY KEY (ID),  
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Target_Types (
  ID int(11) NOT NULL AUTO_INCREMENT,
  Name varchar(255) NOT NULL,
  PRIMARY KEY (ID),  
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE SYSTEMS (
  ID int(11) NOT NULL AUTO_INCREMENT,
  SYSTEM_Name varchar(255) NOT NULL,
  Config_File varchar(255) NOT NULL,
  STATUS_ID int(11) NOT NULL,
  PRIMARY KEY (ID),  
  FOREIGN KEY(STATUS_ID) REFERENCES X_STATUS(ID),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE TARGETS (
  ID int(11) NOT NULL AUTO_INCREMENT,
  Target_Name varchar(255) NOT NULL,
  Target_Type_ID int(11) NOT NULL,
  IP_Address varchar(255),
  STATUS_ID int(11) NOT NULL,
  Password_ID int(11) NOT NULL,
  System_ID int(11) NOT NULL,
  PRIMARY KEY (ID),  
  FOREIGN KEY(STATUS_ID) REFERENCES X_STATUS(ID),
  FOREIGN KEY(Password_ID) REFERENCES PASSWORDS(ID),
  FOREIGN KEY(System_ID) REFERENCES SYSTEMS(ID),
  FOREIGN KEY(Target_Type_ID) REFERENCES Target_Types(ID),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE TESTRUN (
  ID int(11) NOT NULL AUTO_INCREMENT,
  Name varchar(255) NOT NULL,
  System_ID int(11) NOT NULL,
  STATUS_ID int(11) NOT NULL,
  RESULT_ID int(11) NOT NULL,
  Total_Tests int(11),
  Errors int(11),
  Failures int(11),
  NotRun int(11),
  Inconclusive int(11),
  Ignored int(11),
  Skipped int(11),
  Invalid int(11),
  Elapsed_Time varchar(20),
  Log_file varchar(255),
  XML_file varchar(255),
  TestRun_Manager_ID int(11),
  Remediate int(11),
  FOREIGN KEY(System_ID) REFERENCES SYSTEMS(ID),
  FOREIGN KEY(System_ID) REFERENCES TESTRUN_MANAGER(ID),
  PRIMARY KEY (ID),  
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE TESTSUITES (
  ID int(11) NOT NULL AUTO_INCREMENT,
  Name varchar(255),
  TestRun_ID int(11) NOT NULL,
  STATUS_ID int(11) NOT NULL,
  RESULT_ID int(11) NOT NULL,
  Elapsed_Time varchar(20),
  Asserts int(11),
  PRIMARY KEY (ID),
  FOREIGN KEY(STATUS_ID) REFERENCES X_STATUS(ID),
  FOREIGN KEY(RESULT_ID) REFERENCES X_RESULT(ID),
  FOREIGN KEY(TestRun_ID) REFERENCES TESTRUN(ID),
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE TESTCASES (
  ID int(11) NOT NULL AUTO_INCREMENT,
  Name varchar(255),
  Target_ID int(11) NOT NULL,
  STATUS_ID int(11) NOT NULL,
  RESULT_ID int(11) NOT NULL,
  TEST_SUITE_ID int(11) NOT NULL,
  Elapsed_Time varchar(20),
  Asserts int(11),
  PRIMARY KEY (ID),
  FOREIGN KEY(STATUS_ID) REFERENCES X_STATUS(ID),
  FOREIGN KEY(RESULT_ID) REFERENCES X_RESULT(ID),  
  FOREIGN KEY(TEST_SUITE_ID) REFERENCES TESTSUITES(ID),
  FOREIGN KEY (Target_ID) REFERENCES TARGETS(ID),  
  date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP  
);
